# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: users
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module users.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/users.db
    volumes:
      - ./users:/code/users
      - ./db/:/db/
    ports:
      - "5000:5000"
