"""added first and lastname

Revision ID: 6b2a2c391144
Revises: 9fb33b9f5cdf
Create Date: 2022-04-25 23:32:37.574094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2a2c391144'
down_revision = '9fb33b9f5cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
